Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2021-11, with the labels that each got.

#12 Add namespace option to manager start
  main.go
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#17 Change Kubevirt client modules
  api/v1alpha4/kubevirtmachine_types.go
  controllers/kubevirtmachine_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/kubevirt/utils.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/testing/common.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#20 Update golang.org/x/crypto and switch from RSA to EC keys
  go.mod
  go.sum
  pkg/ssh/utils.go
Labels: cncf-cla: yes, size/M, approved, lgtm, manual-testing-done
