Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2021-12, with the labels that each got.

#15 Add unit test for cluster_node_ssh_keys.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/ssh/cluster_node_ssh_keys_test.go
  pkg/ssh/ssh_suite_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#24 kubevirt CI scripts
  .gitignore
  Dockerfile
  Makefile
  api/v1alpha4/zz_generated.deepcopy.go
  config/kubevirtci/kustomization.yaml
  config/kubevirtci/kustomizeconfig.yaml
  config/kubevirtci/manager_auth_proxy_patch.yaml
  config/kubevirtci/manager_image_patch.yaml
  config/kubevirtci/manager_pull_policy.yaml
  config/kubevirtci/manager_webhook_patch.yaml
  config/kubevirtci/namespace.yaml
  config/kubevirtci/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  hack/functest.sh
  kubevirtci
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#27 Fix an import error in the ssh unit tests
  Makefile
  pkg/ssh/cluster_node_ssh_keys_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#21 Fix node patch and KubevirtMachine addresses change
  api/v1alpha4/kubevirtmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  go.mod
  go.sum
  main.go
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/workloadcluster/mock/workloadcluster_generated.go
  pkg/workloadcluster/workloadcluster.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#28 Improvement of Readme
  README.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#30 Make ssh bootstrap detection optional
  api/v1alpha4/kubevirtmachine_types.go
  api/v1alpha4/kubevirtmachinetemplate_webhook_test.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  hack/functest.sh
  pkg/context/machine_context.go
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/ssh/ssh_command_executor.go
  pkg/testing/common.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#43 Update README.md
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#38 Add unit- and functional test runners based on github actions
  .github/workflows/e2e.yaml
  .github/workflows/test.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#48 added meeting info to the README
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#49 Make secrets for third-party PRs available
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#46 Add Dockerfile to build manager binary and emit production image
  Dockerfile
  config/manager/manager.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#44 Fixes "failed to create VM instance" error
  controllers/kubevirtmachine_controller_test.go
  pkg/kubevirt/machine.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#53 Make integration tests independent of go version changes
  .github/workflows/test.yaml
  kubevirtci
Labels: cncf-cla: yes, approved, size/XS, lgtm

#52 Meetings Details update in README.md
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#39 Support for external infra clusters
  api/v1alpha4/kubevirtcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclusters.yaml
  controllers/kubevirtcluster_controller.go
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  main.go
  pkg/context/machine_context.go
  pkg/infracluster/infracluster.go
  pkg/infracluster/mock/infracluster_generated.go
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/kubevirt/utils.go
  pkg/loadbalancer/loadbalancer.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/ssh/cluster_node_ssh_keys.go
  pkg/ssh/ssh_command_executor.go
  pkg/testing/common.go
  templates/cluster-template-ext-infra.yaml
Labels: cncf-cla: yes, approved, size/XL, lgtm

#54 Versions change: Change api version to v1alpha1
  Makefile
  api/v1alpha1/api_suite_test.go
  api/v1alpha1/condition_consts.go
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/kubevirtcluster_types.go
  api/v1alpha1/kubevirtmachine_types.go
  api/v1alpha1/kubevirtmachinetemplate_types.go
  api/v1alpha1/kubevirtmachinetemplate_webhook.go
  api/v1alpha1/kubevirtmachinetemplate_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  config/crd/kustomization.yaml
  config/webhook/manifests.yaml
  controllers/kubevirtcluster_controller.go
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  main.go
  metadata.yaml
  pkg/context/cluster_context.go
  pkg/context/machine_context.go
  pkg/kubevirt/machine_test.go
  pkg/loadbalancer/loadbalancer.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/ssh/cluster_node_ssh_keys_test.go
  pkg/testing/common.go
  templates/cluster-template.yaml
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#50 Versions changes
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  api/v1alpha1/condition_consts.go
  api/v1alpha1/kubevirtcluster_types.go
  api/v1alpha1/kubevirtmachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  config/crd/kustomization.yaml
  controllers/kubevirtcluster_controller.go
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  go.mod
  go.sum
  kubevirtci
  main.go
  pkg/context/cluster_context.go
  pkg/context/machine_context.go
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/ssh/cluster_node_ssh_keys.go
  pkg/ssh/cluster_node_ssh_keys_test.go
  pkg/testing/common.go
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/XL, ok-to-test, lgtm

#57 Limit github action to run only on the kubernetes-sigs/cluster-api-provider-kubevirt repository
  .github/workflows/e2e.yaml
  .github/workflows/test.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#58 Add unit tests for Machine.Create
  controllers/kubevirtmachine_controller.go
  go.mod
  go.sum
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/testing/common.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#61 Modify KubeVirtMachine API to include entire VM Template section
  api/v1alpha1/kubevirtmachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  pkg/kubevirt/machine_test.go
  pkg/kubevirt/utils.go
  pkg/testing/common.go
  templates/cluster-template-ext-infra.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/XXL, lgtm
