Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-09, with the labels that each got.

#180 tests, artifacts: Fix the version to dl kv dump
  hack/run-e2e.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm

#176 Fix unnecessary double write to ssh key secret
  pkg/ssh/cluster_node_ssh_keys.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#168 template: Add kccm flavor
  Makefile
  config/kccm/kustomization.yaml
  config/rbac/role.yaml
  controllers/kubevirtcluster_controller.go
  hack/kccm-flavor-gen.sh
  kubevirtci
  pkg/testing/common.go
  templates/cluster-template-kccm.yaml
  templates/cluster-template-persistent-storage-kccm.yaml
Labels: cncf-cla: yes, approved, size/XL, ok-to-test, lgtm

#186 kubevirtci: Update guest image to have console
  kubevirtci
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#187 ci: Check make generate has being call
  .github/workflows/test.yaml
  .gitignore
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  hack/boilerplate.generatego.txt
  hack/check-gen.sh
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm
