Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-10, with the labels that each got.

#191 kubevirtci: Refactor fetch mechanism
  .gitignore
  kubevirtci
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#196 Revert "Add passt template"
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  go.mod
  go.sum
  kubevirtci
  templates/cluster-template-passt.yaml
  templates/cluster-template-persistent-storage-kccm.yaml
  templates/cluster-template-persistent-storage.yaml
Labels: cncf-cla: yes, approved, size/XL, ok-to-test, lgtm

#194 update e2e to k8s 1.23.10 guest clusters
  hack/functest.sh
  kubevirtci
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#182 minor docs correction
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#188 owners: Add Quique as owners to some sub directories
  .github/OWNERS
  OWNERS
  e2e/OWNERS
  hack/OWNERS
  templates/OWNERS
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#202 Add and release cluster-template-lb.yaml
  .github/workflows/create_release.yaml
  templates/cluster-template-lb.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm
