Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-02, with the labels that each got.

#86 Pass the GOPROXY variable properly to docker
  Makefile
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#87 Add go-linter to the github action
  .github/workflows/test.yaml
  e2e-tests/create-cluster_test.go
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/kubevirt/utils.go
  pkg/ssh/ssh_command_executor.go
  pkg/ssh/utils.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#88 Sort the imports and reformat all golang files
  CONTRIBUTING.md
  Makefile
  controllers/kubevirtcluster_controller.go
  controllers/kubevirtcluster_controller_test.go
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  controllers/kubevirtmachine_suite_test.go
  e2e-tests/create-cluster_test.go
  hack/tools/tools.go
  main.go
  pkg/context/cluster_context.go
  pkg/context/machine_context.go
  pkg/infracluster/infracluster.go
  pkg/infracluster/mock/infracluster_generated.go
  pkg/kubevirt/kubevirt_suite_test.go
  pkg/kubevirt/utils.go
  pkg/loadbalancer/loadbalancer.go
  pkg/loadbalancer/loadbalancer_suite_test.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/ssh/cluster_node_ssh_keys.go
  pkg/ssh/cluster_node_ssh_keys_test.go
  pkg/testing/common.go
  pkg/workloadcluster/mock/workloadcluster_generated.go
  pkg/workloadcluster/workloadcluster.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#80 expose cluster load balancer spec and metadata via KubevirtCluster resource
  api/v1alpha1/kubevirtcluster_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclusters.yaml
  pkg/loadbalancer/loadbalancer.go
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#91 Add davidvossel to approvers list
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#83 Do not wait for SSH keys if there is an external controller
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  e2e-tests/create-cluster_test.go
  kubevirtci
  pkg/kubevirt/machine.go
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#92 add serivce cidr configuration in template
  templates/cluster-template-ext-infra.yaml
  templates/cluster-template-persistent-storage.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#96 Issue 84 - created image build and push workflow
  .github/workflows/image_build.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#93 Cluster deletion race
  api/v1alpha1/kubevirtmachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  controllers/kubevirtcluster_controller.go
  controllers/kubevirtcluster_controller_test.go
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
  e2e-tests/common.go
  e2e-tests/create-cluster_test.go
  go.mod
  go.sum
  pkg/infracluster/infracluster.go
  pkg/infracluster/mock/infracluster_generated.go
  pkg/workloadcluster/mock/workloadcluster_generated.go
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#99 Fixes KubeVirtMachine segfault during tear down
  controllers/kubevirtmachine_controller.go
  controllers/kubevirtmachine_controller_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#104 Fix a unit test
  .github/workflows/test.yaml
  controllers/kubevirtmachine_controller_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
