Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-05, with the labels that each got.

#134 Add failure printout to the e2e test RunCmd function
  e2e/common_test.go
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#113 Clusterctl integration
  .github/workflows/create_release.yaml
  .gitignore
  Makefile
  clusterctl-settings.json
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/kubevirtci/kustomization.yaml
  config/manager/kustomization.yaml
  controllers/kubevirtcluster_controller.go
  e2e/create-cluster_test.go
  metadata.yaml
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#135 added docs for creating the image-builder image
  docs/our-image-creation-process.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#136 Move to golang 1.18
  .github/workflows/clusterkubevirtadm-test.yaml
  .github/workflows/create_release.yaml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#133 kubevirtci: Add option to interact with the tenant cluster and improve usage (help)
  kubevirtci
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#140 Kubevirtci updates
  kubevirtci
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#141 Kubevirtci metal lb support
  kubevirtci
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm
