Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-01, with the labels that each got.

#59 Create coverage file on unit test in CI
  .github/workflows/e2e.yaml
  .github/workflows/test.yaml
  README.md
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#66 e2e ginkgo/gomega test suite
  Makefile
  e2e-tests/common.go
  e2e-tests/create-cluster_test.go
  e2e-tests/e2e-tests.go
  e2e-tests/e2e_tests_suite_test.go
  e2e-tests/setup_teardown.go
  hack/build-e2e.sh
  hack/functest.sh
  hack/run-e2e.sh
  kubevirtci
Labels: cncf-cla: yes, approved, size/L, lgtm

#67 Add the new --fail-with-job flag to let mkpj fail when the prowjob fails
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#71 Run e2e test also on label events
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#68 make 0.1.x version of kubevirt provider compatible with 1.0.x version of cluster-api
  metadata.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#69 fix API versions in external infra template
  templates/cluster-template-ext-infra.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#75 fix issue #74
  pkg/kubevirt/utils.go
  pkg/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#72 Add unit test for Kubevirt Cluster Controller
  controllers/kubevirtcluster_controller_test.go
  controllers/kubevirtmachine_controller_test.go
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#79 Fix bug in KubevirtCluster Reconciler - endless reconcile loop with external controller
  controllers/kubevirtcluster_controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
