Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-03, with the labels that each got.

#102 returen external IP address for loadbalancer
  controllers/kubevirtcluster_controller.go
  pkg/loadbalancer/loadbalancer.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm

#109 Move to ginkgo v2
  api/v1alpha1/api_suite_test.go
  api/v1alpha1/kubevirtmachinetemplate_webhook_test.go
  controllers/kubevirtcluster_controller_test.go
  controllers/kubevirtmachine_controller_test.go
  controllers/kubevirtmachine_suite_test.go
  e2e-tests/create-cluster_test.go
  e2e-tests/e2e_tests_suite_test.go
  go.mod
  go.sum
  hack/build-e2e.sh
  pkg/kubevirt/kubevirt_suite_test.go
  pkg/kubevirt/machine_test.go
  pkg/loadbalancer/loadbalancer_suite_test.go
  pkg/loadbalancer/loadbalancer_test.go
  pkg/ssh/cluster_node_ssh_keys_test.go
  pkg/ssh/ssh_suite_test.go
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#117 Add nirarg to the approvers list
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, lgtm

#111 Added new CLI named clusterkubevirtadm, to manage the infra cluster
  .github/workflows/clusterkubevirtadm-test.yaml
  .github/workflows/e2e.yaml
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  clusterkubevirtadm/cmd/apply/apply.go
  clusterkubevirtadm/cmd/create/create.go
  clusterkubevirtadm/cmd/credentials/apply.go
  clusterkubevirtadm/cmd/credentials/create.go
  clusterkubevirtadm/cmd/credentials/credentials.go
  clusterkubevirtadm/cmd/credentials/credentials_suit_test.go
  clusterkubevirtadm/cmd/credentials/credentials_test.go
  clusterkubevirtadm/cmd/get/get.go
  clusterkubevirtadm/cmd/get/kubeconfig/get.go
  clusterkubevirtadm/cmd/get/kubeconfig/kubeconfig_suit_test.go
  clusterkubevirtadm/cmd/get/kubeconfig/kubeconfig_test.go
  clusterkubevirtadm/cmd/root.go
  clusterkubevirtadm/common/consts.go
  clusterkubevirtadm/common/utils.go
  clusterkubevirtadm/docs.go
  clusterkubevirtadm/main.go
  go.mod
  go.sum
  pkg/kubevirt/machine_factory.go
Labels: cncf-cla: yes, approved, size/XXL, ok-to-test, lgtm

#118 Add nunnatsa to the approvers list
  OWNERS
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#119 Add missing go compiler to the e2e test
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#120 This PR is a hotfix for the broken CI, it fixes a typo in the e2e workflow
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#121 clusterkubevirtadm-fix 2
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#122 Fix clusterkubevirtadm-linux-amd64 calling from e2e cluster creation workflow
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#123 Change clusterkubevirtadm to use --kubeconfig flag
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#125 Restore the E2E test to not use clusterkubevirtadm
  .github/workflows/e2e.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm
