Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2022-11, with the labels that each got.

#204 Add docs PCI passthrough
  docs/pci_passthrough.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#207 Remove the IMAGE_REPO env var from all the temlates
  Dockerfile
  Makefile
  hack/functest.sh
  kubevirtci
  templates/cluster-template-ext-infra.yaml
  templates/cluster-template-kccm.yaml
  templates/cluster-template-lb.yaml
  templates/cluster-template-persistent-storage-kccm.yaml
  templates/cluster-template-persistent-storage.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm

#208 Allow podman to push images to insecure kubevirtci registry
  kubevirtci
Labels: cncf-cla: yes, approved, size/XS, ok-to-test, lgtm

#206 Bump kubevirt to 0.58
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  e2e/create-cluster_test.go
  go.mod
  go.sum
  kubevirtci
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#209 release: Add all the cluster template flavors
  .github/workflows/create_release.yaml
  Makefile
  hack/kccm-flavor-gen.sh
  templates/cluster-template-lb-kccm.yaml
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#214 templates: Activate net multiqueue
  templates/cluster-template-ext-infra.yaml
  templates/cluster-template-kccm.yaml
  templates/cluster-template-lb-kccm.yaml
  templates/cluster-template-lb.yaml
  templates/cluster-template-persistent-storage-kccm.yaml
  templates/cluster-template-persistent-storage.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/S, ok-to-test, lgtm
