Repository kubernetes-sigs/cluster-api-provider-kubevirt, pull requests merged in 2023-05, with the labels that each got.

#238 condition to use controlPlaneEndpoint values
  controllers/kubevirtcluster_controller.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#239 Add sentinel bootstrap file check modes in CRD
  api/v1alpha1/kubevirtmachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtmachinetemplates.yaml
  pkg/kubevirt/machine.go
  pkg/kubevirt/machine_test.go
  pkg/testing/common.go
  templates/cluster-template-ext-infra.yaml
  templates/cluster-template-kccm.yaml
  templates/cluster-template-lb-kccm.yaml
  templates/cluster-template-lb.yaml
  templates/cluster-template-passt-kccm.yaml
  templates/cluster-template-persistent-storage-kccm.yaml
  templates/cluster-template-persistent-storage.yaml
  templates/cluster-template.yaml
Labels: cncf-cla: yes, approved, size/L, lgtm

#240 update x/net pkg
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, ok-to-test, lgtm

#235 feat: add condition to controlPlaneServiceTemplate in KubevirtCluster…
  api/v1alpha1/kubevirtcluster_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_kubevirtclusters.yaml
  controllers/kubevirtcluster_controller.go
  controllers/kubevirtcluster_controller_test.go
  pkg/testing/common.go
Labels: cncf-cla: yes, size/M, approved, ok-to-test, lgtm
